name: 🔄 Material Design

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"
defaults:
  run:
    working-directory: src/Projektanker.Icons.Avalonia.MaterialDesign

jobs:
  sync:
    name: 🔄 Sync Material Design
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.git-check.outputs.modified }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v5

      - name: 📥 Download repository archive
        run: wget -O archive.zip https://github.com/Templarian/MaterialDesign-SVG/archive/master.zip

      - name: 📦 unzip archive
        run: unzip archive.zip -d temp

      - name: 🧹 Clear Assets directory
        run: rm ./Assets/*

      - name: 🚚 Move *.svg to Assets directory
        run: find temp -iname '*.svg' -type f -exec mv -nv -t 'Assets' -- {} +

      - name: 🧹 Remove temporary files
        run: |
          rm -r ./temp
          rm archive.zip

      - name: ℹ git status
        run: git status

      - name: 🔎 Check for modified files
        id: git-check
        run: echo modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT

      - name: 🟣 Setup
        if: ${{ steps.git-check.outputs.modified == 'true' }}
        uses: actions/setup-dotnet@v5

      - name: 🧪 dotnet test
        if: ${{ steps.git-check.outputs.modified == 'true' }}
        run: dotnet test --configuration Release

      - name: 💬 Create Pull Request
        if: ${{ steps.git-check.outputs.modified == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          branch: material-design
          commit-message: "Material Design icons changed."
          title: "feat(Material Design): 🔄 icons changed."
